name: se7ety_gio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.1.2
  cloudinary_flutter: ^1.3.0
  dartz: ^0.10.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.3
  gap: ^3.0.1
  go_router: ^17.0.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  lottie: ^3.3.2
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1
  svg_provider: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#    - assets/icons/
    
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700